/// <reference types="vite/client" />
/**
 * Web font registration and readiness for musical notation rendering.
 *
 * VexFlow draws every notation glyph with fillText() in one SMuFL font. Guidonica
 * imports VexFlow's font-free `vexflow/core` build and self-hosts "Guidonica Notation",
 * a renamed Bravura subset generated by scripts/build-music-font.py (ADR 0058). VexFlow
 * draws no text, so no text font is loaded.
 *
 * When measures or clefs are drawn onto an HTML5 2D Canvas before the font has decoded
 * and mounted in the font subsystem, the canvas engine rasterizes missing glyphs
 * (blank rectangular tofu), which are then permanently baked into offscreen canvas
 * bitmaps (ADR 0012).
 */
import { VexFlow } from 'vexflow/core';
import notationFontUrl from './fonts/guidonica-notation.woff2?url';

/** Bravura's glyphs under a new name: the OFL reserves "Bravura" for the unmodified font. */
export const MUSIC_FONT_FAMILY = 'Guidonica Notation';
const MUSIC_FONT_PROBE = `20px "${MUSIC_FONT_FAMILY}"`;

VexFlow.setFonts(MUSIC_FONT_FAMILY);

/** Registers the face once at module load, so the download starts with the app. */
const musicFontLoad: Promise<unknown> = registerMusicFont();

function registerMusicFont(): Promise<unknown> {
  if (typeof document === 'undefined' || !('fonts' in document) || typeof FontFace === 'undefined') {
    return Promise.resolve();
  }
  const face = new FontFace(MUSIC_FONT_FAMILY, `url(${notationFontUrl}) format('woff2')`, {
    display: 'block',
  });
  document.fonts.add(face);
  // A failed fetch is handled by waitForMusicFonts' timeout fallback
  return face.load().catch(() => undefined);
}

/**
 * Synchronously checks whether the music font is loaded and available to the
 * HTML5 2D Canvas rasterizer.
 */
export function isMusicFontReady(): boolean {
  if (typeof document === 'undefined' || !('fonts' in document)) {
    return true;
  }
  return document.fonts.check(MUSIC_FONT_PROBE);
}

/**
 * Asynchronously awaits full readiness of the music font. Guarantees that subsequent
 * VexFlow canvas rendering operations will not produce missing glyph rectangles.
 */
export async function waitForMusicFonts(): Promise<void> {
  if (typeof document === 'undefined' || !('fonts' in document)) {
    return;
  }

  // Fast-path: return immediately if the notation font is already verified
  if (isMusicFontReady()) {
    return;
  }

  try {
    await Promise.all([
      musicFontLoad,
      document.fonts.load(MUSIC_FONT_PROBE),
      // Solfège label face (self-hosted, ADR 0060); a failed fetch falls back to system-ui silently
      document.fonts.load('700 12px "Alegreya Sans"').catch(() => []),
      document.fonts.ready,
    ]);
  } catch {
    // Fallback if specific font load throws: wait for document.fonts.ready with safety timeout
    await Promise.race([
      document.fonts.ready,
      new Promise<void>((resolve) => setTimeout(resolve, 1500)),
    ]);
  }

  // Verification poll: ensure the font rasterizer has committed the face to the font set
  const maxWaitMs = 2000;
  const startTime = performance.now();
  while (!isMusicFontReady() && performance.now() - startTime < maxWaitMs) {
    await new Promise<void>((resolve) => setTimeout(resolve, 16));
  }
}
